// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrLR9DK_bpwg7D9Osoy41QsoFkNiHDobU',
    appId: '1:398935399770:web:c6fce9afedcb7b09012763',
    messagingSenderId: '398935399770',
    projectId: 'mobile-app-fix',
    authDomain: 'mobile-app-fix.firebaseapp.com',
    databaseURL: 'https://mobile-app-fix-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-fix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE-1HCJED2rLkH5x0ut3n38VVUdw2ojnw',
    appId: '1:398935399770:android:931cfc00ef6187c0012763',
    messagingSenderId: '398935399770',
    projectId: 'mobile-app-fix',
    databaseURL: 'https://mobile-app-fix-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-fix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzhB3e-dGDnPGMYkZsHRZ9KpqypAucc4',
    appId: '1:398935399770:ios:b46ec7b57730ae23012763',
    messagingSenderId: '398935399770',
    projectId: 'mobile-app-fix',
    databaseURL: 'https://mobile-app-fix-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-fix.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceRequestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSzhB3e-dGDnPGMYkZsHRZ9KpqypAucc4',
    appId: '1:398935399770:ios:b46ec7b57730ae23012763',
    messagingSenderId: '398935399770',
    projectId: 'mobile-app-fix',
    databaseURL: 'https://mobile-app-fix-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-fix.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceRequestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrLR9DK_bpwg7D9Osoy41QsoFkNiHDobU',
    appId: '1:398935399770:web:7073373cedd379d7012763',
    messagingSenderId: '398935399770',
    projectId: 'mobile-app-fix',
    authDomain: 'mobile-app-fix.firebaseapp.com',
    databaseURL: 'https://mobile-app-fix-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-fix.firebasestorage.app',
  );
}
